stylesheets/file-icons.less
... and for clojure script too.
=> Using the clojure icon

stylesheets/file-icons.less, stylesheets/icons.less
Here's a few more common ruby files.
=> More common ruby files

stylesheets/file-icons.less
Added entries for the three common CFML file extensions.
Created example files using these extensions.
=> Added ColdFusion icon support

stylesheets/file-icons.less
Add Makefile icon ,add .config icon .manifest icon
=> Add Makefile icon ,add .config icon .manifest icon

stylesheets/file-icons.less
Ref: https://github.com/remy/nodemon
=> Add nodemon support

stylesheets/file-icons.less, stylesheets/icons.less
(Apologies for the extra two superfluous commits!)
=> Adding support for config files (.ini, .properties, .toml)

stylesheets/file-icons.less
=> Resolve .es6 as JS icon

index.coffee, stylesheets/file-icons.less
See: https://github.com/DanBrooker/file-icons/issues/96
I did also some improvements in the code, to use more CoffeeScript syntax and have more readability with some break lines between functions. Codestyle is more consistant.
=> option: colour icons only if file is modified

stylesheets/colors.less, stylesheets/file-icons.less
I added the files to the Ren'Py engine (based on Python) using the icon's own Python with pink (added the pink in colors.less) and its binary.
=> Added Ren'Py Script Files

styles/file-icons.less, styles/icons.less
Add icons for 
- TemplateToolkit not realy an icon but looks very similar to the original icon http://www.template-toolkit.org/ (if it isn't ok i will make a pull request without TT )
- SQL
- Windows specific extensions .bat .cmd .exe .com .reg
=> Add TemplateToolkit, SQL, Windows specific files

styles/items.less
=> Fix icons in tabs

styles/file-icons.less
=> use medium-blue coffee icon for iced-coffee-script files

styles/file-icons.less
Went ahead and implemented #169
=> use git-icon for gitignore, gitattributes and gitmodules files

styles/file-icons.less, styles/icons.less
I added missing .jsp, .jade examples. I also added .htm example with
new icon declaration. I modified .sass, .scss icons colors from purple
to pink (more accurate to product logo) and changed icon to be more
readable.
=> Added .jsp, .jade, .htm examples with new .htm icon and corrected .sass / .scss icons.

styles/file-icons.less
=> Use gear icon for .csslintrc and .csscomb.json

styles/file-icons.less, styles/icons.less
- add .svg files support via Icomoon icon
Closes #196
=> add .svg files support

styles/file-icons.less
=> added package json to have the npm logo icon

styles/file-icons.less
=> Add ico file support

styles/file-icons.less
=> added files .react.js to be formatted with react icon

styles/file-icons.less, styles/icons.less
Should look something like this:
=> Added icon for Dart language

README.md
Mainly for beginners but helpful for quick access.
[Preview link](https://github.com/pcanterini/file-icons/blob/824b440e840eddffa55e0825971c988597e75b9f/README.md)
=> Add installation note to readme for quick use

styles/file-icons.less
I just want a `.tsx` file icon.
Color may change, but i think `dark-blue` is ok.
=> add .tsx icon

styles/items.less
=> Fixes appearance of bottom border of inactive tabs

styles/file-icons.less
=> Add icon for .htpasswd and improve .htaccess rule

styles/file-icons.less
Issue: https://github.com/DanBrooker/file-icons/issues/278
=> Add icon support for JSON5 (.json5)

styles/file-icons.less
=> Use gear icon for .lesshintrc

styles/file-icons.less
=> Adding PKGBUILD and ebuild file types to shell syntax highlighting

styles/file-icons.less
This pull request is me adding the following file extensions/names:
* `.desktop`
* `.directory`
* `.menu`
* `_service`
* `_osc`
* `.install`
=> Adding extra file extensions

styles/file-icons.less
Add ".C" extension to the list of C file extensions
=> Provide c-icon to files with .C extension

CHANGELOG.md, styles/file-icons.less
Use ‘.pem’ icon and change color to blue
=> Support Certificate ('.crt', '.key')

CHANGELOG.md, styles/file-icons.less
Hello. I noticed that `eslintrc.js` wasn't picking up Eslint icon due to positioning before JavaScript decl, looking at the code it looks like this is how this kind of thing is normally handled. Added a reference to the examples folder so you can see.
This is only my second time doing a pull request so forgive me if going about it all wrong, or there is anything else I can do. Thanks for awesome package!
=> Eslintrcjs fix

styles/file-icons.less, styles/icons.less
+ updated devicons font file
+ removed trailing whitespace according to .editorconfig
=> Added icons for CSS preprocessors - Less, Stylus

styles/file-icons.less, styles/icons.less
[Relevant discussion here](https://github.com/DanBrooker/file-icons/pull/371#issuecomment-220987151).
=> Revert "Added icons for CSS preprocessors - Less, Stylus"

styles/file-icons.less
Add support for more variations of webpack config files.
Now supports "standard" environment configuration files like `webpack.production.config.js` and `webpack-development.config.js` as well as all other files containing the combination of `webpack` and `.config.` (really unusual combination for non webpack config files)
=> Improve webpack support.

styles/file-icons.less, styles/icons.less
also tweaked the colour and positioning
.dsql changes should be complete now.
=> Updated .dsql to microsoft's sql server icon in mfizz

CHANGELOG.md, styles/file-icons.less
Hello, Description about this pull request is below.
`.inputrc` provides configuration for readline which supports shell input.
https://en.wikipedia.org/wiki/GNU_Readline
=> Add .inputrc support

CHANGELOG.md, styles/file-icons.less
Uses the existing Docker icon for the following files:
* [Docker Compose](https://docs.docker.com/compose/compose-file) (`docker-compose.*`)
* [Docker Sync](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration) (`docker-sync.yml`)
=> Add support for docker-compose and docker-sync

CHANGELOG.md, styles/file-icons.less
=> Add support for XHTML files (fix #460)

config.cson
https://github.com/Microsoft/nodejstools
See https://github.com/Microsoft/nodejstools/wiki/Projects#project-types for more details on the created project files.
=> Added support for Visual Studio NodeJS project files

config.cson
This is a Fastlane configuration file.
=> Add Appfile support

config.cson, lib/icons/.icondb.js
Add swagger.yaml and swagger.yml as acceptable patterns for swagger icon
=> Additional swagger extensions

config.cson
Use the same icon as Snakefiles
=> add *.smk support

CHANGELOG.md, config.cson
Vue CLI 3 added a `vue.config.js` file to config Vue projects.
This PR add the Vue icon for this file.
=> Support vue.config.js file

config.cson
Icon for https://github.com/file-icons/vscode/pull/49
=> Add support .wix files

styles/icons.less
Updated link for custom icons which was no longer valid.
=> Updated link to icon set

CHANGELOG.md, config.cson
Adding config for [Stitches](https://stitches.dev) Icon
I've added the Icon to the icon repo, PR here: https://github.com/file-icons/icons/pull/78
=> Add Stitches Icon

CHANGELOG.md, config.cson, package.json
Since the tss style files are "almost" css I use the same icons :smile:
=> Support for TSS files (Appcelerator Titanium)

CHANGELOG.md, config.cson
Hello there 👋🏼 
This PR adds support for Elixir's Heex templates (`.heex` as well as `.html.heex`) using existing rules.
Thank you for your work on this project!
=> Add Elixir Heex templates
