- stylesheets/items.less
I wasn't sure if the classes should be kept or if i only should use classnames (for backward compatibility). I decided to use the new custom elements
If you would like to only use classes, then this is the fix:
```less
@pane-tab-selector: ~'.pane .tab-bar .tab .title';
```
Fixes: https://github.com/DanBrooker/file-icons/issues/104
> Fix tab bar regression of Atom v 0.172

- stylesheets/file-icons.less
- stylesheets/items.less
Hey there, it looks like with the new Atom changes, some selectors aren't catching and the icons are missing from the tabs. This PR includes fixes as suggested by Atom's Deprecation Cop.
> Icons missing on tabs in Atom 0.174.0

- stylesheets/items.less
Turns out that was easy. Tabs that don't belong to an editor don't have a `data-path` attribute in the title. Since this is only about file-type icons, you can just make the selector a bit more specific.
Fixes #103
> only show filetype icon for tabs that have a path

- stylesheets/file-icons.less
I use .jshintignore as part of JSHint, it is just a plain text file so didn't add any color to the icon.
> Added jshintignore mapping

- styles/file-icons.less
Set the `.eslintrc` and `.eslintignore` files to use the gear icon.
> Added eslint icons

- styles/file-icons.less
Gulp resolve automatically _gulpfile.babel.js_ as a gulpfile.
> Added the support of babel interpretor for gulpfile

- styles/file-icons.less
- styles/icons.less
I added icons for three files associated with the F# language, source-, script- and signature files (.fs, .fsx and .fsi). The icon comes from the Devicons-font.
I also added three example-files.
> Added F# icon from Devicon and example files

- styles/items.less
Nice to see icons in tabs finally! :)
I've noticed they are a bit down and also italicized when the tab in temp mode. This PR bring following changes:
before
after
before
after
> Align tab icons & keep normal style in temp mode

- styles/file-icons.less
Now recognises `Cargo.toml` and `Cargo.lock` files.
> Adding package icon for Cargo config files.

- styles/file-icons.less
I chose dark-blue because of the brackets of the IPython logo.
Thanks for your work!
> Add icon for IPython (*.ipy) files.

- styles/file-icons.less
Moved Cargo.toml later in file so that it should get set separately from other .toml files. Changed colour for .toml icon so that it's noticeably easier to see on darker backgrounds.
> Reordering fix so Cargo.toml gets set correctly

- styles/file-icons.less
Hello,
This PR adds example file for `.cshtml` - a custom extension used for C# based HTML pages using
Razor syntax, a commonly used templating language  in ASP .NET web development.
The icon for `.cshtml` file is using HTML5 icon and medium red color to be somehow similar to
one color from official MS logo colors:
I think that used red color is somehow optimal for ASP.NET, as others are either already used or used by Atom to highlight Git changes (so I haven't used green).
Thanks!
> Add support for .cshtml - a C#/ASP.NET Razor file extension

- styles/file-icons.less
changed scala icon color `.medium-green` from  to `.medium-red` for issue #203
> changed scala icon color .medium-green from to .medium-red

- styles/icons.less
Since the icon is pretty small in height, top should be a bit lower.
Before:
After:
> Align node-icon

- styles/file-icons.less
HJSON (http://hjson.org/) is a superset of JSON.
> Add .hjson

- styles/file-icons.less
Which were overriden by new styles in 59d8d110d4d35a14b242352855a83d489ba75f8a
> Removed old styles for eslint

- styles/file-icons.less
- styles/icons.less
I use JSX without React a lot, and I don't like that my JSX files have the React specific logo. Maybe we could change the icon to incorporate the non-opinionated JSX icon?
> Set JSX file icon to the JSX icon

- styles/file-icons.less
PowerShell Modules have a `.psm1` extension.
See: https://technet.microsoft.com/en-us/library/dd878324
>A script module is a file (.psm1) that contains any valid Windows PowerShell code. Script developers and administrators can use this type of module to create modules whose members include functions, variables, and more.
> PowerShell module extension correction.

- styles/file-icons.less
- styles/icons.less
I've always felt Rust's icon was being displayed a little too small, so I've submitted a PR to adjust it:
> Increase size of Rust icon

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- package.json
This took all afternoon, but hey, better late than never. =)
@ckross01 : As suggested by [keepachangelog.com](http://keepachangelog.com/), I've added a section at the top that encompasses all unpublished modifications. It'll be up to you or @DanBrooker to make sure this gets updated with the name/number of a new release (so `[Unreleased]` becomes `[1.6.15]` or what-have-you).
I've also followed KACL.com's convention of making each release section linked to a comparison page (if you click the version numbers, you'll see). These were added manually with footnote links (at the bottom of the changelog's source code). This will also need to be updated when cutting a new release.
I've covered the basics of what should be done in a new section in `CONTRIBUTING.md`.
> Fix #262: Maintain a changelog

- CHANGELOG.md
- index.coffee
This PR simply adds a helper class to the `atom-workspace` element to disable Seti UI's icons when this package is activated.
Granted, this won't do a thing until https://github.com/jesseweed/seti-ui/pull/216 gets merged into upstream.
> Add workspace class to disable Seti UI icons when active

- styles/file-icons.less
There are lots of examples of code that people write two or more ```webpack.config.*.js``` files, like ```webpack.config.development.js``` and ```webpack.config.production.js```. Webpack also recognises automatically ```webpack.config.babel.js``` and transpiles it with Babel before uses it (I actually use this way).
Perhaps someone can use other extension but ```.js```. I gess begining ```webpack.config.``` is pretty good.
> Improve webpack icon support

- styles/file-icons.less
Hi,
Adding .ad file extension for asciidoc and .spacemacs for Emacs Lisp, as they were missing. 
Thanks for your time,
Brenton
> Adding extra file extensions

- CHANGELOG.md
- styles/file-icons.less
Add support for files named `composer.phar` exactly. [`CHANGELOG`](https://github.com/zanderbaldwin/file-icons/blob/e01a4d45b3a140c20ae395acfdc6b34301e5ed22/CHANGELOG.md) has been updated.
> Support Composer Executables

- styles/file-icons.less
For people using https://github.com/netzpirat/haml-coffee or https://github.com/emilioforrer/haml_coffee_assets to write haml files in coffeescript templates (used with angular etc)
> Add hamlc extension for haml icon

- CHANGELOG.md
- styles/file-icons.less
Currently, the PDF icon displays in colour regardless of the "Coloured" setting, and is aligned to the left (should be in the center). This PR fixes both those issues.
> Fix PDF on colourless setting, and center align the icon

- CHANGELOG.md
- styles/file-icons.less
Similar to how the Bash config files are handled, all the ZSH config files without the dot now display the shell icon properly
> Add in support for ZSH config files without the dot

- CHANGELOG.md
- styles/file-icons.less
- styles/icons.less
- Adjusted size/alignment of the Python icon (current one is too small)
- Added in quite a few icon listings for Node, Python and Ruby files
> Add in support for more Node, Python and Ruby files

- styles/file-icons.less
Adding the `.zsh-theme` file extension to the list of Zsh shell script file types.
> Adding zsh-theme file extension

- CHANGELOG.md
- styles/file-icons.less
Add uppercase FORTRAN file extensions. Many compilers use file extension case to indicate preprocessing for FORTRAN.
> Add support for preprocessed FORTRAN file extensions

- CHANGELOG.md
- styles/file-icons.less
Was going to contribute a yin-yang icon SVG as this is what the filetype's icon would be, but seeing as one already exists for YANG I guess that isn't really necessary.
> Add support for Danmakufu

- styles/file-icons.less
- styles/icons.less
Hi,
In this commit I am adding Ubuntu icons and using them for Snappy package files (namely snapcraft.yaml and .snap files). 
Thanks for your time,
Brenton
> Adding Ubuntu icons for Snappy package files

- styles/file-icons.less
This just adds the eslint icon (which needs to be updated to the new logo, but will do that on https://github.com/Alhadis/FileIcons repo) to `.eslintcache` files.
> Add .eslintcache icon

- styles/file-icons.less
- styles/icons.less
> Back on the server, Mocha will attempt to load ./test/mocha.opts as a configuration file of sorts.
> Add support for Mocha .opts extension

- styles/file-icons.less
.dsql is used by Microsoft's Parallel Data Warehouse. For lack of a corporate branding, a little bit of google search yielded a lean towards purple. So here it is as light-purple. Anyway - the focus is on differentiation from the standard sql icon rather than a specific colour.
> Added .dsql file detection

- styles/file-icons.less
There is already icon for `Vagrantfile` so I added the same icon for `.vagrant` directory
> Add icon for .vagrant directory

- styles/file-icons.less
Hashicorp Terraform supports `.tfvars` file extension in addition to standard `.tf` - this PR adds standard Terraform icon for these files.
`.tfvars` support is being mentioned in official Terraform documentation: https://www.terraform.io/intro/getting-started/variables.html
> Add Terraform icon to .tfvars files

- CHANGELOG.md
- styles/file-icons.less
Uses existing Bower icon for:
* [Bowerfile](https://github.com/rharriso/bower-rails#ruby-dsl-configuration) is used by Bower Rails as a DSL configuration file.
> Add support for Bowerfile

- CHANGELOG.md
- styles/file-icons.less
Uses existing Zsh icon for:
- [`Antigen`](https://github.com/zsh-users/antigen) - A plugin manager
for zsh
- [`Prezto`](https://github.com/sorin-ionescu/prezto) - The
configuration framework for Zsh
> Add support for .antigen and .zpreztorc

- styles/file-icons.less
`.mjs` seems to be the current candidate for the ES2015 module extension in Node.js - let's add support for it.
I found [this article](https://nodesource.com/blog/es-modules-and-node-js-hard-choices) that backs up this claim, if it is of interest. :)
Thanks!
> JavaScript: Add .mjs extension support

- CHANGELOG.md
- styles/file-icons.less
[Vash](https://github.com/kirbysayshi/vash) is a [Razor Syntax](https://www.asp.net/web-pages/overview/getting-started/introducing-razor-syntax-c)-based template engine that has been recently introduced in the alternatives offered by the [Express application generator](https://expressjs.com/en/starter/generator.html).
Nothing too fancy in this PR, just used the standard HTML icon with a red colour, since `.vash` files are kind of similar to `.cshtml`.
I'm not sure I understand the part "*remember to replace [Unreleased] with the name of the version you're cutting*" in the `CONTRIBUTING.md` guide, but here's my shot at it.
File-icons is one of the plugins that make Atom great, so thanks and keep up the good work!
> Add support for Vash template files

- CHANGELOG.md
- styles/file-icons.less
- styles/icons.less
**Source Map** files are used to map minified code to source code. We can then read and debug compiled code in its original source.
I leveraged the Font Awesome icon **[fa-map](http://fontawesome.io/icon/map/)** for both CSS (`.css.map`) and Javascript (`.js.map`) files. They both match the CSS and Javascript colours assigned to the (`.css`) and (`.js`) files.
I added two example files in the example directory and updated the CHANGELOG.md file accordingly.
Thanks for the great Atom package!
> This is my first pull request ever. Please tell me if something is off.
> Add support for CSS and Javascript source map files

- config.cson
Now it's possible to specify file extensions for `.postcssrc` (same case of `.eslintrc`).
https://github.com/michael-ciniawsky/postcss-load-config/releases/tag/v1.2.0
> Support file extensions for .postcssrc

- config.cson
- Add `.gitlab` folder
- Only support `.gitlab-ci.yml`, not `.gitlab-ci.yaml` or `.GITLAB-CI.YML`
> Tweak GitLab file matches

- config.cson
Since `protractor.conf.js` is not strictly required filename, let's also support `protractor.config.js` which is consistent filename when you also have `(webpack|jasmine|postcss).config.js`.
Probably, the same thing could be done to Karma...
> Add `protractor.config.js` to protractor icon matches

- config.cson
When using [VueJS webpack template](https://github.com/vuejs-templates/webpack), we get several webpack files:
- webpack.base.conf.js
- webpack.dev.conf.js
- webpack.prod.conf.js
- webpack.test.conf.js
with no webpack icon :(
I just updated the webpack regex to `/webpack(\.\w+)?\.conf(ig)?\./i` to match these files
> First PR ever, I hope I did it right :)
> Support webpack.*.conf.js files

- config.cson
- lib/icons/.icondb.js
[stylelint v7.10.0](https://github.com/stylelint/stylelint/releases/tag/7.10.0) introduced cache functionality, with the filename defaults to `.stylelintcache`. I followed the same idea of `.eslint{ignore,cache}` files.
> Support .stylelintcache files

- config.cson
Introduced by npm 5: https://github.com/npm/npm/pull/16244
> Use npm icon for package-lock.json

- config.cson
These files are shipped with current Chart.js releases: https://github.com/chartjs/Chart.js/releases
> Add .min and .bundle support for Chart.js

- CHANGELOG.md
- config.cson
- lib/icons/.icondb.js
I was just browsing my home directory and thought it would be fun to have the `.docker` directory visually show that it has to do with Docker. 🙂
> Add support for ".docker" directories

- CHANGELOG.md
- config.cson
- lib/icons/.icondb.js
> Associate .flow with flowtype js

- lib/consumers/archive-view.js
The package throws exception on Windows when archive-view uses it in archive with nested files/directories.
Not sure if importing `path` is ok here or it should go somewhere in [Atom-FS package](https://github.com/Alhadis/Atom-FS) for abstraction.
> Fixed exception in archive consumer.

- config.cson
In my project, we use dash for webpack config file name like webpack.xxx-xxx.config.js.
I updated webpack regex in config.cson.
> Update webpack regex

- config.cson
With Jest v20, `jest.config.js` is a valid config file as well. The current regex was only matching on `jest.config.json`.
:+1: for this lib, btw.
> Update Jest regex

- CHANGELOG.md
- config.cson
- lib/icons/.icondb.js
With ionic >= 2, `ionic.config.json` is a valid config file as well. The current regex was only matching on `ionic.project`.
> Update Ionic regex

- config.cson
- styles/icons.less
I'm not sure why the commit indentation in icons.less is formatted improperly, but with this config.cson color update. and added content charmap I get:
> Fix Imba icon color, implement icon class in icons.less

- config.cson
- lib/icons/.icondb.js
Both dotted and non dotted format are valid. Ref: https://www.appveyor.com/docs/build-configuration/#yaml-file-alternative-naming
> Support `appveyor.yml` and `.appveyor.yml`

- lib/service/strategies/linguist-strategy.js
The 'micromatch' dependency seems to be unusually heavy - when using `atom --profile-startup` this seems to account for over 200ms of activation time! It's extremely straightforward to defer its loading until the "linguist" strategy is actually executed.
> Lazily require the 'micromatch' dependency

- lib/service/icon-service.js
The `FileSystem` module wasn't being notified on resource deletion which
resulted in an inconsistent state of the resource cache. By subscribing
to deletion notifications for files in the project and destroying the
resource if it's cached in the `Filesystem` module, we solve that issue.
Fixes #490
> Notify FileSystem on resource deletion

- config.cson
Babel 7 uses this JavaScript configuration file.
> Add support for .babelrc.js

- lib/service/icon-service.js
When we get a 'deleted' event from `atom.project.onDidChangeFiles` in `IconService`, currently `FileSystem.get` is called - which will create a resource + icon for the file if it hasn't been processed already.
This leads to poor performance when performing e.g. git or hg updates - at least with 'hg' Atom handles Mercurial's atomic file writes as a delete + create, so we end up doing work for every modified file :(
An easy workaround (although it reaches into `FileSystem.paths` is to check `FileSystem.paths.has` before calling `FileSystem.get`.
I manually tested this by linking my local file-icons, running an `hg update`, and verifying that resources weren't created for modified files (despite hitting the 'deleted' case.)
> Avoid unnecessarily creating resources for deleted files

- lib/main.js
- lib/storage.js
- package.json
This uses https://www.npmjs.com/package/lru-cache to impose an upper bound on the size of storage. I chose 10000 - the storage size is a barely tolerable ~1MB at that point (the overhead of serializing that is about 10ms, which is tolerable I guess. If you're willing to tolerate something lower I think that might be better.)
There's nothing too tricky about this - I searched for all references to `data.paths` and fixed them up appropriately.
- I bumped the version to 4.
- I used "serialize" instead of "serialise" to be consistent with Atom's APIs - let me know if you'd prefer the latter! :P
- My editor stripped out the trailing whitespace - hopefully that's OK.
Testing:
- `atom --dev --test test` is still working fine.
- I restarted Atom and inspected `storage = …
> Use LRUCache for storage (max: 10000)

- config.cson
See also: https://babeljs.io/docs/en/next/babelconfigjs.html. Regex borrowed from Webpack entry.
> Add support for `babel.config.js`

- CHANGELOG.md
- config.cson
Related to #751 - I added support for Ansible icon on the rest of the role-folders (vars,defaults,meta,tests). They seemed a bit lonely without the nice Ansible icon 😄 
@brandonkal, I read you had some preferences regarding variable files vs. tasks and handlers, so feel free to criticize on the coloring here. Same goes for you, @Alhadis. 
This is a humble PR, so feel free to shoot me down if you guys don't like it.
> Added icons for rest of Ansible folders

- config.cson
Both `.esdoc.json` and `.esdoc.js` are default file names for the ESDoc configuration file, as per the [official documentation](https://esdoc.org/manual/usage.html)
> Update matching pattern for ESDoc

- config.cson
- lib/icons/.icondb.js
Just updating the current Elixir file extensions with a recent [addition] (https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-assigns-and-liveeex-templates) of `.leex`
> Added new Elixir Phoenix Live View file extension

- CHANGELOG.md
- config.cson
- lib/icons/.icondb.js
When the Arch Linux icon was added #382, a matching for files named `PKGBUILD` was added for the Arch Linux icon, but it wasn’t removed for the Shell icon. This PR fixes this.
> Use Arch Linux instead of terminal icon for PKGBUILD files

- CHANGELOG.md
- config.cson
- lib/icons/.icondb.js
Thanks for this package!
I added support for `poetry.lock`, a lock file for Poetry, a dependency manager for Python. It uses the `config-python` icon.
> Add support for poetry.lock

- lib/service/strategies/path-strategy.js
Following up on #823, there is [one alert remaining by LGTM for file-icons/atom](https://lgtm.com/projects/g/file-icons/atom/snapshot/cb1f640186142881873a78e594433f754d07105c/files/lib/service/strategies/path-strategy.js?sort=name&dir=ASC&mode=heatmap#V38). This time it's a super simple "problem" so I figured I can open a PR immediately :smile: 
In the file [path-strategy.js](https://github.com/file-icons/atom/blob/850b9a24c3b3588c270fcceca9209f8756146b1f/lib/service/strategies/path-strategy.js) there is an assignment to a variable which is not subsequently used. Namely, in [the function `matchIcon`](https://github.com/file-icons/atom/blob/850b9a24c3b3588c270fcceca9209f8756146b1f/lib/service/strategies/path-strategy.js#L31-L62) a value is assigned to the local variable `icon` and this is …
> Refactor unused variable assignment

- lib/service/icon-service.js
Fixes issues mentioned in #693 
Summary: Whenever a file is "deleted" & "created" instantaneously, which can happen when formatters are run or git modifies the file, then the resource for the file gets destroyed and never gets created again. This adds a check to see if the file is created in the same call.
> Check if the same file is created before removing from FileSystem

- config.cson
yamllint uses [3 possible configuration file names](https://yamllint.readthedocs.io/en/stable/configuration.html#configuration). This pull adds next 2:
- `.yamllint.yaml`
- `.yamllint.yml`
> Add '.yamllint.yaml' and '.yamllint.yml' matchs

- .gitignore
At least judging by the `.gitignore`, it looks like you want to let potential contributors choose their own package manager. With `pnpm` gaining popularity, I figured that you would want this ignored, too.
> Ignore `pnpm-lock.yaml`

- config.cson
update regex to `eslint\.config\.(m|c|)[jt]s` to match all js/ts files options:
from [https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file)
> eslint.config.js
eslint.config.mjs
eslint.config.cjs
eslint.config.ts
eslint.config.mts
eslint.config.cts
> Support ESlint 9 config files
